# Generated by Django 4.2.5 on 2023-10-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicApi', '0002_alter_room_rm_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='vote_to_skip',
            new_name='votes_to_skip',
        ),
    ]
