# Generated by Django 4.2.5 on 2023-10-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApi', '0003_rename_vote_to_skip_room_votes_to_skip'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
